version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - restore_cache: # special step to restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Setup Dependencies
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run: # run tests
        name: Run Test and Coverage
        command: |
          npm test -- --coverage
    - store_artifacts:
        path: /coverage
    - store_test_results:
        path: /coverage

  deploy-staging:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - restore_cache: # special step to restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Setup Dependencies
        command: npm install
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - add_ssh_keys:
        fingerprints:
          - "36:f2:66:a2:f4:9a:96:e6:e6:83:58:1e:7b:39:e7:36"
    - run:
        name: Deploy to Github Pages
        command: |
          npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy-staging:
        requires:
        - build
        filters:
          branches:
            only: master
